<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonaNest.Domain\PersonaNest.Domain.csproj" />
    <ProjectReference Include="..\PersonaNest.Infrastructure\PersonaNest.Infrastructure.csproj" />
  </ItemGroup>

</Project>
